import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="max-w-7xl w-full mx-auto min-h-screen border border-gray-700 rounded-2xl mt-8 px-8 py-4 ">
          {children}
        </div>
      </body>
    </html>
  );
}
